apiVersion: v1
description: Manifests, dashboards, and alerting rules for end-to-end Kubernetes cluster monitoring.
engine: gotpl
maintainers:
  - name: 3DSIM
    email: webteam@3dsim.com
name: kube-prometheus
sources:
  - https://github.com/3dsim/kube-prometheus-chart
version: 0.1.1
